# Generated by Django 3.1.6 on 2021-04-16 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='test.jpg', upload_to='user_pics')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[users.models.validate_input])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[users.models.validate_input])),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True, validators=[users.models.validate_input])),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
