# Generated by Django 3.1.6 on 2021-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210416_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
