# Generated by Django 3.1.6 on 2021-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userslog', '0002_auto_20210329_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food',
            field=models.CharField(max_length=10, null=True, verbose_name='선호하는음식'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='몸무게'),
        ),
    ]
