# Generated by Django 3.1.6 on 2021-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userslog', '0003_auto_20210329_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(max_length=10, null=True, verbose_name='사는 지역'),
        ),
    ]
