# Generated by Django 3.1.6 on 2021-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userslog', '0004_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(default='', max_length=10, verbose_name='사는 지역'),
        ),
    ]
