# Generated by Django 3.1.6 on 2021-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='운동 및 활동')),
                ('calories1', models.IntegerField(default=0, verbose_name='51kg')),
                ('calories2', models.IntegerField(default=0, verbose_name='71kg')),
                ('calories3', models.IntegerField(default=0, verbose_name='81kg')),
                ('calories4', models.IntegerField(default=0, verbose_name='95kg')),
                ('hour', models.FloatField(default=0, verbose_name='한시간 당 소모 칼로리')),
            ],
        ),
    ]
