# Generated by Django 3.1.6 on 2021-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='eximg',
            field=models.ImageField(blank='True', upload_to='', verbose_name='운동이미지'),
        ),
    ]
