# Generated by Django 3.1.6 on 2021-04-16 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='plan.jpg', upload_to='plan_pics')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('fats', models.FloatField(null=True)),
                ('proteins', models.FloatField(null=True)),
                ('carbs', models.FloatField(null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('meal_cat', models.ForeignKey(default='BreakFast', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.mealcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Food Item',
            },
        ),
        migrations.CreateModel(
            name='PastRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_goal', models.PositiveIntegerField(null=True)),
                ('cal_consumed', models.PositiveIntegerField(null=True)),
                ('date_of_record', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Past Record',
            },
        ),
    ]
