# Generated by Django 3.1.6 on 2021-04-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_lifestyle'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PlanCategory',
        ),
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name_plural': 'Meal Categories'},
        ),
        migrations.AlterModelOptions(
            name='plancategory',
            options={'verbose_name_plural': 'Plan Categories'},
        ),
    ]
