# Generated by Django 3.1.6 on 2021-04-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210416_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditems',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
