# Generated by Django 3.1.6 on 2021-04-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ounce', models.IntegerField()),
                ('Grams', models.IntegerField()),
                ('Lb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('protien', models.FloatField()),
                ('per_how_much_gram', models.IntegerField()),
                ('FoodType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='check.foodtype')),
                ('MealType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='check.meals')),
            ],
        ),
    ]
