# Generated by Django 3.1.6 on 2021-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0002_auto_20210331_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodclass',
            name='cabor',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='탄수화물'),
        ),
        migrations.AlterField(
            model_name='foodclass',
            name='fat',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='지방'),
        ),
        migrations.AlterField(
            model_name='foodclass',
            name='protein',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='단백질'),
        ),
    ]
