# Generated by Django 3.1.6 on 2021-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0006_auto_20210331_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodclass',
            name='once',
            field=models.FloatField(default=0, verbose_name='1회 제공량'),
        ),
    ]
