# Generated by Django 3.1.6 on 2021-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0008_auto_20210331_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodclass',
            name='calories',
            field=models.FloatField(default=0, verbose_name='칼로리'),
        ),
    ]
